In [6]:
import numpy as np
arr = np.array([4, 5, 6])
print(arr)

[4 5 6]


In [14]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[:,:])
print(arr[0:2,0:3])
print(arr[0:,1:3])
print(arr[-1:,:])
print(arr[-2:-1,-3:-1])
print(arr[0:-1,0:-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 9 10 11 12]]
[[6 7]]
[[1 2 3]
 [5 6 7]]


In [2]:
import numpy as np
arr = np.array([[99,22,33],[44,77,66]])
print(arr[:,1:-1])
print(arr)

[[22]
 [77]]
[[99 22 33]
 [44 77 66]]


In [61]:
import numpy as np
arr = np.array([[99,22,33],[44,77,66]])
print(arr[0,0])
print(arr[0,1])
print(arr[0,2])
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])



99
22
33
44
77
66


In [72]:
import numpy as np
org_arr = np.array([[99,22,33],[44,77,66]])
print(org_arr)
copy_arr = org_arr
copy_arr[1,2] = 13
print(copy_arr)

[[99 22 33]
 [44 77 66]]
[[99 22 33]
 [44 77 13]]


In [23]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2),axis = 0)
print(arr)

[1 2 3 4 5 6]


In [21]:
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [9]:
arr = np.stack((arr1,arr2),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [32]:
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [72]:
arr = np.array([1,2,3,4,5,6]) 
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [60]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [74]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [80]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [97]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [88]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.vsplit(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [108]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Rank of A:",np.linalg.matrix_rank(arr))
print("\nTrace of A:",np.trace(arr))
print("\nDeterminant of A :", np.linalg.det(arr))
print("\nInverse of A:\n", np.linalg.inv(arr))
print("\nMatrix A raised to power 3:\n",np.linalg.matrix_power(arr,3))

Rank of A: 2

Trace of A: 15

Determinant of A : -9.51619735392994e-16

Inverse of A:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]

Matrix A raised to power 3:
 [[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]


In [117]:
import numpy as np
from numpy import linalg as LA 
A = np.array([[1,2,3],[3,2,1],[1,0,-1]]) 
w, v = LA.eig(A) 
print(v)
print(w)

[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]
[ 4.31662479e+00 -2.31662479e+00  2.13869201e-17]


In [119]:
from numpy import random
x=random.randint(100,size=(5))
print(x)

[79 65 23  4 16]


In [123]:
from numpy import random
x=random.rand()
print(x)

0.05883023009150734


In [127]:
from numpy import random
x=random.randint(100,size=(8))
print(x)

[21 76 21 63 60 65 62 19]


In [6]:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr = np.array(