In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
print(arr.shape)

(5,)


In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)
print(arr.size)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8


In [ ]:
import numpy as np
arr0 = np.arange(20)
arr1 = np.arange(1,21)

print(arr0)
print(arr1)
print(arr1.shape)

In [68]:
arr = np.arange(1,21).reshape(4,5)
print(arr)
newarr = arr.reshape(2, 5, 2)
newarr1 = arr.reshape(2,2,5)
print(newarr)

print(newarr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [102]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [106]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [104]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2,2,2)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
import numpy as np
arr = np.arange(25)
print(arr)
arr1 = np.reshape(5,5)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


ValueError: cannot reshape array of size 1 into shape (5,)

In [19]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [32]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
arr = np.full((3, 3),2)
print(arr)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [19]:
arr = np.random.rand(3,3)
print(arr)

[[0.90898892 0.72713377 0.50110657]
 [0.70223965 0.4188485  0.62899677]
 [0.77463625 0.83443279 0.45329567]]


In [71]:
arr = np.full((3,3,3),4)
print(arr)
print(arr.ndim)

[[[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]]
3


In [23]:
arr = np.eye(4, 4)
arr1 = np.empty((3,3))
print(arr)
print(arr1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.90898892 0.72713377 0.50110657]
 [0.70223965 0.4188485  0.62899677]
 [0.77463625 0.83443279 0.45329567]]


In [61]:
arr = np.linspace(5,20,num=4)
print(arr)

[ 5. 10. 15. 20.]


In [81]:
arr  = np.array([1,1,1,1,1],ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 1 1 1 1]]]]]]]]]]
10


In [86]:
arr = np.array([[1,2,3,4,7],[5,6,7,8,8],[9,10,11,12,2],[4,7,8,9,10]])
print(arr[1:3,2:3])
print(arr[:,:])

[[ 7]
 [11]]
[[ 1  2  3  4  7]
 [ 5  6  7  8  8]
 [ 9 10 11 12  2]
 [ 4  7  8  9 10]]


In [121]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[0:-2,:])
print(arr[0:-1,0:-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]]
[[1 2 3]
 [5 6 7]]


In [129]:
print(arr[:,1:4:2]) # even col

[[ 2  4]
 [ 6  8]
 [10 12]]


In [123]:
print(arr[:,0:4:2]) # odd column

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [125]:
print(arr[:,0:4:3]) #first column and last column

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [131]:
print(arr[0:3:2,:]) # odd row

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [135]:
print(arr[1:4:2,:]) #even row

[[5 6 7 8]]


In [141]:
print(arr[0:3:2,:]) #first row and last row

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [143]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [175]:
arr[[0,-1]] = arr[[-1,0]] #swapping row
print(arr)


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [163]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [179]:
arr[:,[0,-1]]=arr[:,[-1,0]] #swapping column
print(arr)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [173]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [72]:
org_arr = np.array([[11,22,33],[44,55,66]])
print(org_arr)
copy_arr = org_arr
copy_arr[1,2] = 77
print(org_arr)
print(copy_arr)


[[11 22 33]
 [44 55 66]]
[[11 22 33]
 [44 55 77]]
[[11 22 33]
 [44 55 77]]


In [78]:
arr = np.array([1,2,3,4,5,6]) #1D
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [94]:
arr = np.array([[1,2,3,4],[5,6,7,8]]) #2D
for x in arr:
    print(x)
for x in arr:
    for y in x:
        print(y)
for x in np.nditer(arr):
    print(x)

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [98]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in arr:
    for y in x:
        print(y)
for x in arr:
    for y in x:
        for z in y:
            print(z)
for x in np.nditer(arr):
    print(x)

[1 2]
[3 4]
[5 6]
[7 8]
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [186]:
arr = np.arange(1,13).reshape(2,2,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [192]:
print(arr[0][1][1])
print(arr[1][1][2])

5
12


In [194]:
import numpy as np 
a = np.array([1, 2, 3, 4]) 
print(a+5) 
print(a-2)  
print(a*10) 
print(a/2)


[6 7 8 9]
[-1  0  1  2]
[10 20 30 40]
[0.5 1.  1.5 2. ]


In [198]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a*b)

[ 6  8 10 12]
[ 5 12 21 32]


In [200]:
a = np.array([[1,2],[3,4]])
print(a+5)

[[6 7]
 [8 9]]


In [202]:
b = np.array([[5,6],[7,8]])
print(a+b)

[[ 6  8]
 [10 12]]


In [216]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.max(axis=1)) #row = 1 col = 0
print(arr.max(axis=0))
print(arr.min(axis=0))
print(arr.sum())
print(arr.sum(axis=1))
print(arr.sum(axis=0))

[3 6 9]
[7 8 9]
[1 2 3]
45
[ 6 15 24]
[12 15 18]


In [218]:
import numpy as np 
a = np.array([0, np.pi/2, np.pi]) 
print ( np.sin(a)) 
a = np.array([0, 1, 2, 3]) 
print ( np.exp(a)) 
print ( np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]


In [220]:
arr = np.power(2,4)
print(arr)

16


In [222]:
arr = np.gcd(12,32)
print(arr)

4


In [235]:
arr = np.lcm(15,9)
print(arr)

45


In [237]:
a = np.array([2,4,6])
b = np.array([8,10,12])
arr = np.lcm(a,b)
print(arr)

[ 8 20 12]


In [239]:
print(np.std(a))

1.632993161855452


In [241]:
print(np.var(b))

2.6666666666666665


In [245]:
import numpy as np
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
print(np.add(a, b)) 
print(np.subtract(a,b))
print(np.multiply(a, b)) 
print(np.divide(a, b))
print(np.remainder(a,b))
print(np.mod(a,b))
print(np.power(a,b)) 
print(np.reciprocal(a)) 

[10  7  9 11  8]
[ 4 -1 -1 -1 -6]
[21 12 20 30  7]
[2.33333333 0.75       0.8        0.83333333 0.14285714]
[1 3 4 5 1]
[1 3 4 5 1]
[  343    81  1024 15625     1]
[0 0 0 0 1]


In [249]:
arr = np.full((3,3),1,dtype = 'complex')
print(arr)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [251]:
import numpy as np
complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print("Original array:")
print(complex_num)
print("\nSorted a given complex array using the real part first, then the imaginary part.")
print(np.sort_complex(complex_num)) 

Original array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

Sorted a given complex array using the real part first, then the imaginary part.
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


In [255]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(np.add(a,b))

[ 6  8 10 12]
[ 6  8 10 12]


In [265]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(type(arr))
print(np.power(arr,2))

(3, 4)
12
2
int32
<class 'numpy.ndarray'>
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [269]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]


In [275]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=1))
print(np.concatenate((a,b),axis=0))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
